# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 20.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    # Install the app and all its dependencies
    npm install
  displayName: 'npm install and build'
 
- script: |
    URL=https://www.uts.edu.au
    # Install the Axe CLI accessibility testing tool
    #npm install -g axe-cli
    #axe --help
    docker pull gcr.io/check-accessibility/check-accessibility:0.1

    # Run the Axe accessibility tests (if there's more pages to test, just give it a comma-separated list of URLs)
    # Appending --exit will cause the tests to exit 1 if problems are found. This could be handy but I'm not using it yet
    #axe $URLS_COMMA_SEPARATED --exit
    ACCESSIBILITY_PROBLEMS_JSON=`docker run -e URL=$URL gcr.io/check-accessibility/check-accessibility:0.1`
    echo $ACCESSIBILITY_PROBLEM_JSON
    
    # If test fails, exit 1 to fail this step in the pipeline
    if [ $? -ne 0 ]; then kill $APP_PID && exit 1; fi

  displayName: 'Run Docker accessibility tests'
  
