# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 20.04'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    URL=https://www.uts.edu.au

    docker pull gcr.io/check-accessibility/check-accessibility:0.1

    docker run -e URL=$URL gcr.io/check-accessibility/check-accessibility:0.1 > accessibility_results.json
    cat accessibility_results.json
    
    # If test fails, exit 1 to fail this step in the pipeline
    #if [ $? -ne 0 ]; then kill $APP_PID && exit 1; fi

  displayName: 'Run Docker accessibility tests'
  
